modLoader="javafml"
loaderVersion="[47,)"
license="Academic Free License v3.0"

[[mods]]
modId="primogemcraft"
version="2413"
displayName="原石工艺"
displayURL="https://www.mcmod.cn/class/10429.html"
logoFile="logo.png"
credits="Created using mod maker MCreator - https://mcreator.net/about"
authors="Pepper某人, MCreator"
description="一个暂时啥也不是的mod"

[[dependencies.primogemcraft]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20.1]"
    ordering="NONE"
    side="BOTH"




